# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: test1
#  vmImage: ubuntu-latest

stages:
- stage: s1
  displayName: stage1
  jobs:
    - job: j1
      steps:
        - bash: |
            sleep 20
            echo "hello"
    - job: j2
      steps:
        - bash: |
            sleep 20
            echo "world"

- stage: s2
  displayName: stage2
  jobs:
    - job: j3
      steps:
        - bash: |
            sleep 20
            echo "hello"
    - job: j4
      steps:
        - bash: |
            sleep 20
            echo "world" 
    - job: j5
      steps:
        - task: Kubernetes@1
          displayName: kubectl create
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceEndpoint: crp-k8s
            command: create
            arguments: namespace test
                

            

